name: "my first workflow"
on: 
  push:
    branches:
      - main
      - 'mona/octocat'
      - 'releases/**'
    # Sequence of patterns matched against refs/tags
    tags:
      - v2
      - v1.*
  jobs:
    terraformInit:
      name: intiwa
      runs-on: abhi-maharaj
      steps:
      - name: abhi-maharaj
        run: echo abhi-maharaj
